#include "hgles_context_state.cpp"
#include "hgles_input_glfw.cpp"
#include "hgles_input_interface.cpp"
#include "hgles_input_pi.cpp"
#include "hgles_window_glfw.cpp"
#include "hgles_window_interface.cpp"
#include "hgles_glad.c"
